# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from voucherify_client.models.campaigns_update_discount_coupons_campaign import CampaignsUpdateDiscountCouponsCampaign
from voucherify_client.models.campaigns_update_gift_campaign import CampaignsUpdateGiftCampaign
from voucherify_client.models.campaigns_update_giveaway_campaign import CampaignsUpdateGiveawayCampaign
from voucherify_client.models.campaigns_update_loyalty_campaign import CampaignsUpdateLoyaltyCampaign
from voucherify_client.models.campaigns_update_promotion_campaign import CampaignsUpdatePromotionCampaign
from voucherify_client.models.campaigns_update_referral_campaign import CampaignsUpdateReferralCampaign
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

CAMPAIGNS_UPDATE_REQUEST_BODY_ONE_OF_SCHEMAS = ["CampaignsUpdateDiscountCouponsCampaign", "CampaignsUpdateGiftCampaign", "CampaignsUpdateGiveawayCampaign", "CampaignsUpdateLoyaltyCampaign", "CampaignsUpdatePromotionCampaign", "CampaignsUpdateReferralCampaign"]

class CampaignsUpdateRequestBody(BaseModel):
    """
    Request body schema for **PUT** `/campaigns/{campaignId}`.
    """
    # data type: CampaignsUpdateDiscountCouponsCampaign
    oneof_schema_1_validator: Optional[CampaignsUpdateDiscountCouponsCampaign] = None
    # data type: CampaignsUpdateReferralCampaign
    oneof_schema_2_validator: Optional[CampaignsUpdateReferralCampaign] = None
    # data type: CampaignsUpdateGiftCampaign
    oneof_schema_3_validator: Optional[CampaignsUpdateGiftCampaign] = None
    # data type: CampaignsUpdateLoyaltyCampaign
    oneof_schema_4_validator: Optional[CampaignsUpdateLoyaltyCampaign] = None
    # data type: CampaignsUpdatePromotionCampaign
    oneof_schema_5_validator: Optional[CampaignsUpdatePromotionCampaign] = None
    # data type: CampaignsUpdateGiveawayCampaign
    oneof_schema_6_validator: Optional[CampaignsUpdateGiveawayCampaign] = None
    if TYPE_CHECKING:
        actual_instance: Union[CampaignsUpdateDiscountCouponsCampaign, CampaignsUpdateGiftCampaign, CampaignsUpdateGiveawayCampaign, CampaignsUpdateLoyaltyCampaign, CampaignsUpdatePromotionCampaign, CampaignsUpdateReferralCampaign]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(CAMPAIGNS_UPDATE_REQUEST_BODY_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = CampaignsUpdateRequestBody.construct()
        error_messages = []
        match = 0
        # validate data type: CampaignsUpdateDiscountCouponsCampaign
        if not isinstance(v, CampaignsUpdateDiscountCouponsCampaign):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CampaignsUpdateDiscountCouponsCampaign`")
        else:
            match += 1
        # validate data type: CampaignsUpdateReferralCampaign
        if not isinstance(v, CampaignsUpdateReferralCampaign):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CampaignsUpdateReferralCampaign`")
        else:
            match += 1
        # validate data type: CampaignsUpdateGiftCampaign
        if not isinstance(v, CampaignsUpdateGiftCampaign):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CampaignsUpdateGiftCampaign`")
        else:
            match += 1
        # validate data type: CampaignsUpdateLoyaltyCampaign
        if not isinstance(v, CampaignsUpdateLoyaltyCampaign):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CampaignsUpdateLoyaltyCampaign`")
        else:
            match += 1
        # validate data type: CampaignsUpdatePromotionCampaign
        if not isinstance(v, CampaignsUpdatePromotionCampaign):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CampaignsUpdatePromotionCampaign`")
        else:
            match += 1
        # validate data type: CampaignsUpdateGiveawayCampaign
        if not isinstance(v, CampaignsUpdateGiveawayCampaign):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CampaignsUpdateGiveawayCampaign`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in CampaignsUpdateRequestBody with oneOf schemas: CampaignsUpdateDiscountCouponsCampaign, CampaignsUpdateGiftCampaign, CampaignsUpdateGiveawayCampaign, CampaignsUpdateLoyaltyCampaign, CampaignsUpdatePromotionCampaign, CampaignsUpdateReferralCampaign. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in CampaignsUpdateRequestBody with oneOf schemas: CampaignsUpdateDiscountCouponsCampaign, CampaignsUpdateGiftCampaign, CampaignsUpdateGiveawayCampaign, CampaignsUpdateLoyaltyCampaign, CampaignsUpdatePromotionCampaign, CampaignsUpdateReferralCampaign. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> CampaignsUpdateRequestBody:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> CampaignsUpdateRequestBody:
        """Returns the object represented by the json string"""
        instance = CampaignsUpdateRequestBody.construct()
        error_messages = []
        match = 0

        # deserialize data into CampaignsUpdateDiscountCouponsCampaign
        try:
            instance.actual_instance = CampaignsUpdateDiscountCouponsCampaign.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CampaignsUpdateReferralCampaign
        try:
            instance.actual_instance = CampaignsUpdateReferralCampaign.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CampaignsUpdateGiftCampaign
        try:
            instance.actual_instance = CampaignsUpdateGiftCampaign.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CampaignsUpdateLoyaltyCampaign
        try:
            instance.actual_instance = CampaignsUpdateLoyaltyCampaign.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CampaignsUpdatePromotionCampaign
        try:
            instance.actual_instance = CampaignsUpdatePromotionCampaign.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CampaignsUpdateGiveawayCampaign
        try:
            instance.actual_instance = CampaignsUpdateGiveawayCampaign.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CampaignsUpdateRequestBody with oneOf schemas: CampaignsUpdateDiscountCouponsCampaign, CampaignsUpdateGiftCampaign, CampaignsUpdateGiveawayCampaign, CampaignsUpdateLoyaltyCampaign, CampaignsUpdatePromotionCampaign, CampaignsUpdateReferralCampaign. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CampaignsUpdateRequestBody with oneOf schemas: CampaignsUpdateDiscountCouponsCampaign, CampaignsUpdateGiftCampaign, CampaignsUpdateGiveawayCampaign, CampaignsUpdateLoyaltyCampaign, CampaignsUpdatePromotionCampaign, CampaignsUpdateReferralCampaign. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


