# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict
from pydantic import BaseModel, Field, StrictInt

class CustomerLoyalty(BaseModel):
    """
    CustomerLoyalty
    """
    points: StrictInt = Field(..., description="Customer's loyalty points.")
    referred_customers: StrictInt = Field(..., description="Total number of customers referred by the customer.")
    campaigns: Dict[str, Any] = Field(..., description="Contains campaigns with details about point balances and how many customers were referred by the customer.")
    __properties = ["points", "referred_customers", "campaigns"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CustomerLoyalty:
        """Create an instance of CustomerLoyalty from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CustomerLoyalty:
        """Create an instance of CustomerLoyalty from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CustomerLoyalty.parse_obj(obj)

        _obj = CustomerLoyalty.parse_obj({
            "points": obj.get("points"),
            "referred_customers": obj.get("referred_customers"),
            "campaigns": obj.get("campaigns")
        })
        return _obj


