# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ExportVoucherOrder(str, Enum):
    """
    ExportVoucherOrder
    """

    """
    allowed enum values
    """
    CODE = 'code'
    MINUS_CODE = '-code'
    VOUCHER_TYPE = 'voucher_type'
    MINUS_VOUCHER_TYPE = '-voucher_type'
    VALUE = 'value'
    MINUS_VALUE = '-value'
    DISCOUNT_TYPE = 'discount_type'
    MINUS_DISCOUNT_TYPE = '-discount_type'
    CAMPAIGN = 'campaign'
    MINUS_CAMPAIGN = '-campaign'
    CATEGORY = 'category'
    MINUS_CATEGORY = '-category'
    START_DATE = 'start_date'
    MINUS_START_DATE = '-start_date'
    EXPIRATION_DATE = 'expiration_date'
    MINUS_EXPIRATION_DATE = '-expiration_date'
    GIFT_BALANCE = 'gift_balance'
    MINUS_GIFT_BALANCE = '-gift_balance'
    LOYALTY_BALANCE = 'loyalty_balance'
    MINUS_LOYALTY_BALANCE = '-loyalty_balance'
    REDEMPTION_QUANTITY = 'redemption_quantity'
    MINUS_REDEMPTION_QUANTITY = '-redemption_quantity'
    REDEMPTION_COUNT = 'redemption_count'
    MINUS_REDEMPTION_COUNT = '-redemption_count'
    ACTIVE = 'active'
    MINUS_ACTIVE = '-active'
    QR_CODE = 'qr_code'
    MINUS_QR_CODE = '-qr_code'
    BAR_CODE = 'bar_code'
    MINUS_BAR_CODE = '-bar_code'
    METADATA = 'metadata'
    MINUS_METADATA = '-metadata'
    ID = 'id'
    MINUS_ID = '-id'
    IS_REFERRAL_CODE = 'is_referral_code'
    MINUS_IS_REFERRAL_CODE = '-is_referral_code'
    CREATED_AT = 'created_at'
    MINUS_CREATED_AT = '-created_at'
    UPDATED_AT = 'updated_at'
    MINUS_UPDATED_AT = '-updated_at'
    VALIDITY_TIMEFRAME_INTERVAL = 'validity_timeframe_interval'
    MINUS_VALIDITY_TIMEFRAME_INTERVAL = '-validity_timeframe_interval'
    VALIDITY_TIMEFRAME_DURATION = 'validity_timeframe_duration'
    MINUS_VALIDITY_TIMEFRAME_DURATION = '-validity_timeframe_duration'
    VALIDITY_DAY_OF_WEEK = 'validity_day_of_week'
    MINUS_VALIDITY_DAY_OF_WEEK = '-validity_day_of_week'
    DISCOUNT_AMOUNT_LIMIT = 'discount_amount_limit'
    MINUS_DISCOUNT_AMOUNT_LIMIT = '-discount_amount_limit'
    CAMPAIGN_ID = 'campaign_id'
    MINUS_CAMPAIGN_ID = '-campaign_id'
    ADDITIONAL_INFO = 'additional_info'
    MINUS_ADDITIONAL_INFO = '-additional_info'
    CUSTOMER_ID = 'customer_id'
    MINUS_CUSTOMER_ID = '-customer_id'
    DISCOUNT_UNIT_TYPE = 'discount_unit_type'
    MINUS_DISCOUNT_UNIT_TYPE = '-discount_unit_type'
    DISCOUNT_UNIT_EFFECT = 'discount_unit_effect'
    MINUS_DISCOUNT_UNIT_EFFECT = '-discount_unit_effect'
    CUSTOMER_SOURCE_ID = 'customer_source_id'
    MINUS_CUSTOMER_SOURCE_ID = '-customer_source_id'

    @classmethod
    def from_json(cls, json_str: str) -> ExportVoucherOrder:
        """Create an instance of ExportVoucherOrder from a JSON string"""
        return ExportVoucherOrder(json.loads(json_str))


