# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel
from voucherify_client.models.junction import Junction
from voucherify_client.models.loyalties_points_expiration_export_create_response_body_parameters_filters_campaign_id import LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersCampaignId
from voucherify_client.models.loyalties_points_expiration_export_create_response_body_parameters_filters_voucher_id import LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersVoucherId

class LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters(BaseModel):
    """
    Data filters used to narrow down the data records to be returned in the export.  # noqa: E501
    """
    junction: Optional[Junction] = None
    voucher_id: Optional[LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersVoucherId] = None
    campaign_id: Optional[LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersCampaignId] = None
    __properties = ["junction", "voucher_id", "campaign_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters:
        """Create an instance of LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of voucher_id
        if self.voucher_id:
            _dict['voucher_id'] = self.voucher_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of campaign_id
        if self.campaign_id:
            _dict['campaign_id'] = self.campaign_id.to_dict()
        # set to None if voucher_id (nullable) is None
        # and __fields_set__ contains the field
        if self.voucher_id is None and "voucher_id" in self.__fields_set__:
            _dict['voucher_id'] = None

        # set to None if campaign_id (nullable) is None
        # and __fields_set__ contains the field
        if self.campaign_id is None and "campaign_id" in self.__fields_set__:
            _dict['campaign_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters:
        """Create an instance of LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.parse_obj(obj)

        _obj = LoyaltiesPointsExpirationExportCreateResponseBodyParametersFilters.parse_obj({
            "junction": obj.get("junction"),
            "voucher_id": LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersVoucherId.from_dict(obj.get("voucher_id")) if obj.get("voucher_id") is not None else None,
            "campaign_id": LoyaltiesPointsExpirationExportCreateResponseBodyParametersFiltersCampaignId.from_dict(obj.get("campaign_id")) if obj.get("campaign_id") is not None else None
        })
        return _obj


