# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ParameterVoucherTypeListPublications(str, Enum):
    """
    ParameterVoucherTypeListPublications
    """

    """
    allowed enum values
    """
    DISCOUNT = 'discount'
    LOYALTY = 'loyalty'
    LUCKY_DRAW = 'lucky_draw'

    @classmethod
    def from_json(cls, json_str: str) -> ParameterVoucherTypeListPublications:
        """Create an instance of ParameterVoucherTypeListPublications from a JSON string"""
        return ParameterVoucherTypeListPublications(json.loads(json_str))


