# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field

class ParameterCreatedBeforeAfter(BaseModel):
    """
    ParameterCreatedBeforeAfter
    """
    before: Optional[datetime] = Field(None, description="Timestamp representing the date and time before the voucher was created in ISO 8601 format.")
    after: Optional[datetime] = Field(None, description="Timestamp representing the date and time after the voucher was created in ISO 8601 format.")
    __properties = ["before", "after"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ParameterCreatedBeforeAfter:
        """Create an instance of ParameterCreatedBeforeAfter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ParameterCreatedBeforeAfter:
        """Create an instance of ParameterCreatedBeforeAfter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ParameterCreatedBeforeAfter.parse_obj(obj)

        _obj = ParameterCreatedBeforeAfter.parse_obj({
            "before": obj.get("before"),
            "after": obj.get("after")
        })
        return _obj


