# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ParameterOrderListRedeemables(str, Enum):
    """
    ParameterOrderListRedeemables
    """

    """
    allowed enum values
    """
    ID = 'id'
    MINUS_ID = '-id'

    @classmethod
    def from_json(cls, json_str: str) -> ParameterOrderListRedeemables:
        """Create an instance of ParameterOrderListRedeemables from a JSON string"""
        return ParameterOrderListRedeemables(json.loads(json_str))


