# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel
from voucherify_client.models.promotions_tiers_create_response_body_summary_orders import PromotionsTiersCreateResponseBodySummaryOrders
from voucherify_client.models.promotions_tiers_create_response_body_summary_redemptions import PromotionsTiersCreateResponseBodySummaryRedemptions

class PromotionsTiersCreateResponseBodySummary(BaseModel):
    """
    Contains statistics about promotion tier redemptions and orders.  # noqa: E501
    """
    redemptions: Optional[PromotionsTiersCreateResponseBodySummaryRedemptions] = None
    orders: Optional[PromotionsTiersCreateResponseBodySummaryOrders] = None
    __properties = ["redemptions", "orders"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PromotionsTiersCreateResponseBodySummary:
        """Create an instance of PromotionsTiersCreateResponseBodySummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of redemptions
        if self.redemptions:
            _dict['redemptions'] = self.redemptions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of orders
        if self.orders:
            _dict['orders'] = self.orders.to_dict()
        # set to None if redemptions (nullable) is None
        # and __fields_set__ contains the field
        if self.redemptions is None and "redemptions" in self.__fields_set__:
            _dict['redemptions'] = None

        # set to None if orders (nullable) is None
        # and __fields_set__ contains the field
        if self.orders is None and "orders" in self.__fields_set__:
            _dict['orders'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PromotionsTiersCreateResponseBodySummary:
        """Create an instance of PromotionsTiersCreateResponseBodySummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PromotionsTiersCreateResponseBodySummary.parse_obj(obj)

        _obj = PromotionsTiersCreateResponseBodySummary.parse_obj({
            "redemptions": PromotionsTiersCreateResponseBodySummaryRedemptions.from_dict(obj.get("redemptions")) if obj.get("redemptions") is not None else None,
            "orders": PromotionsTiersCreateResponseBodySummaryOrders.from_dict(obj.get("orders")) if obj.get("orders") is not None else None
        })
        return _obj


