# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from voucherify_client.models.resource_types import ResourceTypes

class QualificationsOptionFiltersResourceTypeConditions(BaseModel):
    """
    Data filters used to narrow the data records to be returned in the result.  # noqa: E501
    """
    var_is: Optional[ResourceTypes] = Field(None, alias="$is")
    is_not: Optional[ResourceTypes] = Field(None, alias="$is_not")
    var_in: Optional[conlist(ResourceTypes)] = Field(None, alias="$in", description="Array of qualified redeemables. Accepts more than one value. Returns the resource types entered in the array.")
    not_in: Optional[conlist(ResourceTypes)] = Field(None, alias="$not_in", description="Array of qualified redeemables. Accepts more than one value. Returns the resource types except those entered in the array.")
    __properties = ["$is", "$is_not", "$in", "$not_in"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QualificationsOptionFiltersResourceTypeConditions:
        """Create an instance of QualificationsOptionFiltersResourceTypeConditions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QualificationsOptionFiltersResourceTypeConditions:
        """Create an instance of QualificationsOptionFiltersResourceTypeConditions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QualificationsOptionFiltersResourceTypeConditions.parse_obj(obj)

        _obj = QualificationsOptionFiltersResourceTypeConditions.parse_obj({
            "var_is": obj.get("$is"),
            "is_not": obj.get("$is_not"),
            "var_in": obj.get("$in"),
            "not_in": obj.get("$not_in")
        })
        return _obj


