# coding: utf-8

"""
    Voucherify API

    Voucherify promotion engine REST API. Please see https://docs.voucherify.io/docs for more details.

    The version of the OpenAPI document: v2018-08-01
    Contact: support@voucherify.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class RedeemLoyaltyCardAllOfReward(BaseModel):
    """
    Contains information about the reward that the customer wants to redeem and the number of points the customer is choosing to use for the reward.  # noqa: E501
    """
    id: Optional[StrictStr] = Field(None, description="Unique reward ID assigned by Voucherify. The reward must be assigned to the campaign in order for the user to be able to use the reward.")
    points: Optional[StrictInt] = Field(None, description="The number of loyalty points that the user wants to spend in order to fulfill the order using a **pay with points** reward. The number of points cannot be higher than the current balance on the loyalty card.")
    __properties = ["id", "points"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RedeemLoyaltyCardAllOfReward:
        """Create an instance of RedeemLoyaltyCardAllOfReward from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RedeemLoyaltyCardAllOfReward:
        """Create an instance of RedeemLoyaltyCardAllOfReward from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RedeemLoyaltyCardAllOfReward.parse_obj(obj)

        _obj = RedeemLoyaltyCardAllOfReward.parse_obj({
            "id": obj.get("id"),
            "points": obj.get("points")
        })
        return _obj


